### ISSUE TITLE
Tinker热修复疑问？

### ISSUE THREAD

**Issue by lanjd** [linux-link/Fan#2]
你好，我有个疑问，看见你项目里用了Tinker热修复，同时用了Java 8，不会有问题么？
https://github.com/Tencent/tinker/issues/1210

**Comment by linxu-link** [comment]
这个项目因为服务器的问题，不能下载文件，所以没有测试过tinker。不过，公司项目中使用了java8+tinker，没有出现问题。java8的新特性其实很多，如果只是运用了lambda表达式不会出问题，第三方库中可能会用到新的特性，但是一般不会用tinker去修复第三方库的bug。

**Comment by lanjd** [comment]
好的，我再试试，多谢！
